"""
=============================================================================
FILE: loop.py
DESCRIPTION: 
This is the core Orchestrator of the Multi-Agent Framework.
It manages the lifecycle of the Living Survey through an iterative workflow:
1. Oracle Generation: Uses a separate LLM to generate a Ground Truth for metrics.
2. Actor Execution: Instructs an AI Agent to select relevant papers and write the Markdown.
3. Critic Execution (Reviewer 2): Instantiates a ruthless checker to find and remove 
   hallucinations or ungrounded claims generated by the Actor.
4. Validation & Commit: Computes performance metrics. If the score improves 
   AND at least one paper is integrated, it commits via Git; if it drops 
   (due to errors/hallucinations) or no papers are added, it rolls back.
=============================================================================
"""

import os
import sys
import subprocess
import re
import shutil
from datetime import datetime

# Local environment configuration
os.environ["OPENAI_API_BASE"] = "http://127.0.0.1:9000/v1"
os.environ["OPENAI_API_KEY"] = "none"

def run_command(cmd, capture_output=True):
    """Executes a system shell command and captures its output."""
    print(f"\n[SYSTEM] Executing: {' '.join(cmd) if isinstance(cmd, list) else cmd}")
    result = subprocess.run(cmd, shell=isinstance(cmd, str), text=True, capture_output=capture_output)
    if result.stdout and capture_output:
        print(result.stdout.strip())
    if result.stderr and capture_output and result.returncode != 0:
        print(f"[SYSTEM ERROR] {result.stderr.strip()}")
    return result

def get_lss_metrics(topic):
    """Parses both the real LSS Score and the Integrated Count from prepare.py."""
    res = run_command(f'python prepare.py --eval "{topic}"')
    score = 0.0
    count = 0
    match_score = re.search(r'LSS_SCORE:\s*([0-9.]+)', res.stdout)
    match_count = re.search(r'INTEGRATED_COUNT:\s*([0-9]+)', res.stdout)
    if match_score:
        score = float(match_score.group(1))
    if match_count:
        count = int(match_count.group(1))
    return score, count

def run_autonomous_loop(topic, iterations=1, search_query=None):
    if not search_query:
        search_query = topic

    print(f"==================================================")
    print(f" STARTING LIVING SURVEY: Project '{topic}' | Query: '{search_query}'")
    print(f"==================================================")
    
    # 1. Workspace Initialization
    run_command(f'python prepare.py --init "{topic}"')
    
    clean_name = re.sub(r'[^a-zA-Z0-9]', '_', topic.lower()).strip('_')
    topic_dir = os.path.join("surveys", clean_name)
    
    survey_file = os.path.join(topic_dir, f"{clean_name}.md")
    bib_file = os.path.join(topic_dir, "references.bib")
    fig_script = os.path.join(topic_dir, "generate_figures.py")

    for i in range(1, iterations + 1):
        print(f"\n──────────────────────────────────────────────────")
        print(f" CYCLE {i}/{iterations} - LITERATURE RETRIEVAL")
        print(f"──────────────────────────────────────────────────")
        
        # Fetch new papers
        fetch_res = run_command(f'python prepare.py --fetch "{topic}" "{search_query}"')
        if "Fetched 0" in fetch_res.stdout or fetch_res.returncode != 0:
            print("[STOP] No new papers retrieved. Executing cleanup and terminating.")
            run_command("git checkout .")
            run_command("git clean -fd")
            break
            
        # Baseline measurement
        baseline_score, baseline_count = get_lss_metrics(topic)
        print(f"[METRIC] Starting Baseline LSS Score: {baseline_score} (Integrated: {baseline_count})")

        # =======================================================
        # ORACLE: GROUND TRUTH GENERATION (LLM-as-a-Judge)
        # =======================================================
        print("\n[ORACLE] Generating Ground Truth (LLM-as-a-Judge)...")
        # Passing both the topic and the search query to ensure context-aware evaluation
        run_command(f'python auto_evaluator.py "Main Topic: {topic}. Specific Query: {search_query}"')

        # =======================================================
        # ACTOR AGENT PROMPT
        # =======================================================
        prompt_actor = (
            f"Carefully read the 'new_papers.json' file containing unreleased papers.\n"
            f"1) RELEVANCE SCREENING: Evaluate if each paper is strictly relevant to the topic: '{search_query}'. "
            f"If it is off-topic or outside the required timeframe, discard and ignore it.\n"
            f"2) INTEGRATION: If relevant, integrate a concise analysis into '{survey_file}' using Markdown citations like [^paper_id]. "
            f"EXPANSION RULE: Do NOT delete or summarize any existing text from previous cycles! Add new content by organically expanding existing sections or creating new ones.\n"
            f"3) BIBLIOGRAPHY: Add the new bibliographic entries into '{bib_file}' (leaving existing entries intact).\n"
            f"4) DATA UPDATE: Update TIMELINE_DATA and TAXONOMY_DATA at the beginning of '{fig_script}' by ADDING the new counts to the existing values.\n"
            f"5) CLEANUP: Strictly remove any empty headers without underlying text from '{survey_file}'. The document must only contain fully argued sections!\n"
            f"Do NOT execute terminal commands, do NOT write LaTeX code, just edit the requested files."
        )

        print("\n[AI AGENT - ACTOR] Writing and integrating new literature...")
        run_command(f'uvx --from aider-chat aider --model openai/lab-main --read prepare.py --read program.md --read new_papers.json --yes-always --no-git --message "{prompt_actor}" {survey_file} {bib_file} {fig_script}')

        # =======================================================
        # CRITIC AGENT PROMPT (Reviewer 2)
        # =======================================================
        prompt_critic = (
            f"Act as a ruthless scientific reviewer (Reviewer 2). "
            f"Carefully compare the latest additions in '{survey_file}' with the actual abstracts in 'new_papers.json'.\n"
            f"REVIEW RULES & HISTORICAL MEMORY:\n"
            f"1) RESPECT THE PAST: '{survey_file}' contains citations from previous cycles (already in '{bib_file}'). "
            f"If a citation is NOT in 'new_papers.json' but exists in '{bib_file}', DO NOT DELETE IT! It is historically verified literature.\n"
            f"2) VERIFY NEW ADDITIONS: Examine ONLY claims related to papers from the current 'new_papers.json'. "
            f"Check if the abstract TRULY supports the written text or if there are hallucinations/exaggerations.\n"
            f"3) If you find a single exaggeration, falsehood, or ungrounded data among the NEW papers, delete ONLY that specific flawed sentence/paragraph without touching the rest of the document.\n"
            f"Do NOT invent code, limit yourself to the targeted revision of '{survey_file}'."
        )

        print("\n[AI AGENT - CRITIC] Peer-reviewing and verifying scientific accuracy...")
        run_command(f'uvx --from aider-chat aider --model openai/lab-main --read new_papers.json --read {bib_file} --yes-always --no-git --message "{prompt_critic}" {survey_file}')

        # Generate charts
        print("\n[SYSTEM] Rendering actual charts to disk...")
        run_command(f'python "{fig_script}"')

        # =======================================================
        # METRICS CALCULATION
        # =======================================================
        print("\n[METRICS] Calculating Precision, Recall, and F1-Measure...")
        run_command(f'python evaluate_metrics.py "{clean_name}"')

        # Real Evaluation & Verdict
        new_score, new_count = get_lss_metrics(topic)
        delta_score = round(new_score - baseline_score, 2)
        delta_count = new_count - baseline_count
        
        print(f"\n[VERDICT] LSS Score: {baseline_score} -> {new_score} (Δ {delta_score:+.2f})")
        print(f"[VERDICT] Integrated Papers: {baseline_count} -> {new_count} (Δ {delta_count:+d})")

        if new_score > baseline_score and new_count > baseline_count:
            print("[SUCCESS] Improvement and actual integration confirmed! Executing Git Commit.")
            run_command("git add .")
            run_command(f'git commit -m "feat({clean_name}): integrated {delta_count} valid papers (LSS: {new_score})" ')
        else:
            print("[REJECT] No actual papers integrated or hallucination blocked. Executing Git Reset!")
            run_command("git reset --hard HEAD")
            run_command("git clean -fd")

        # =======================================================
        # JSON LOG ARCHIVING SYSTEM
        # =======================================================
        logs_dir = os.path.join(topic_dir, "eval_logs")
        os.makedirs(logs_dir, exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        if os.path.exists("new_papers.json"):
            new_papers_archive = os.path.join(logs_dir, f"new_papers_{timestamp}.json")
            shutil.move("new_papers.json", new_papers_archive)
            
        if os.path.exists("ground_truth.json"):
            gt_archive = os.path.join(logs_dir, f"ground_truth_{timestamp}.json")
            shutil.move("ground_truth.json", gt_archive)
            
        print(f"[LOG] JSON files successfully archived in: {logs_dir} (Timestamp: {timestamp})")

    print("\n==================================================")
    print(" LOOP SUCCESSFULLY COMPLETED!")
    print("==================================================")
    
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python loop.py \"Project Name\" [cycles] [\"Search Query or Year Filter\"]")
        sys.exit(1)
    
    arg_topic = sys.argv[1]
    arg_iterations = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    arg_query = sys.argv[3] if len(sys.argv) > 3 else None
    
    run_autonomous_loop(arg_topic, arg_iterations, arg_query)